const UNIVERSITY_NAME_ZH_MAP: Record<string, string> = {
  "Carnegie Mellon University": "卡内基梅隆大学",
  "Massachusetts Institute of Technology": "麻省理工学院",
  "Princeton University": "普林斯顿大学",
  "University of California, Berkeley": "加州大学伯克利分校",
  "National University of Singapore": "新加坡国立大学",
  "University College London": "伦敦大学学院",
  "Imperial College London": "帝国理工学院",
  "King's College London": "伦敦国王学院",
  "Columbia Business School": "哥伦比亚大学商学院",
  "London School of Economics and Political Science": "伦敦政治经济学院",
  "University of Warwick": "华威大学",
  "University of Manchester": "曼彻斯特大学",
  "The University of Manchester": "曼彻斯特大学",
  "University of Bristol": "布里斯托大学",
  "University of Southern California": "南加州大学",
  "The Hong Kong University of Science and Technology": "香港科技大学",
  "The University of Hong Kong": "香港大学",
  "The University of British Columbia": "不列颠哥伦比亚大学",
  "The University of Melbourne": "墨尔本大学",
  "Northwestern University": "西北大学",
  "Singapore Management University": "新加坡管理大学",
  "University of Toronto": "多伦多大学",
  "The Chinese University of Hong Kong": "香港中文大学",
  "The University of Edinburgh": "爱丁堡大学",
  "UNSW Sydney": "新南威尔士大学",
  "American Public University System": "美国公立大学系统",
  "Arizona State University Campus Immersion": "亚利桑那州立大学",
  "Brigham Young University": "杨百翰大学",
  "California State University-Fullerton": "加州州立大学富勒顿分校",
  "California State University-Long Beach": "加州州立大学长滩分校",
  "California State University-Northridge": "加州州立大学北岭分校",
  "Florida International University": "佛罗里达国际大学",
  "Grand Canyon University": "大峡谷大学",
  "Indiana University-Bloomington": "印第安纳大学伯明顿分校",
  "Kennesaw State University": "肯尼索州立大学",
  "Liberty University": "自由大学",
  "Michigan State University": "密歇根州立大学",
  "Ohio State University-Main Campus": "俄亥俄州立大学主校区",
  "Pennsylvania State University-Main Campus": "宾夕法尼亚州立大学主校区",
  "Purdue University-Main Campus": "普渡大学西拉斐特校区",
  "Rutgers University-New Brunswick": "罗格斯大学新布朗斯维克分校",
  "San Diego State University": "圣迭戈州立大学",
  "Southern New Hampshire University": "南新罕布什尔大学",
  "Texas A&M University-College Station": "德州农工大学学院站校区",
  "Texas State University": "得州州立大学",
  "Texas Tech University": "得州理工大学",
  "The University of Alabama": "阿拉巴马大学",
  "The University of Texas at Arlington": "得克萨斯大学阿灵顿分校",
  "The University of Texas at Austin": "得克萨斯大学奥斯汀分校",
  "University of Arizona": "亚利桑那大学",
  "University of California-Berkeley": "加州大学伯克利分校",
  "University of California-Davis": "加州大学戴维斯分校",
  "University of California-Los Angeles": "加州大学洛杉矶分校",
  "University of California-San Diego": "加州大学圣迭戈分校",
  "University of Central Florida": "中佛罗里达大学",
  "University of Florida": "佛罗里达大学",
  "University of Houston": "休斯敦大学",
  "University of Illinois Urbana-Champaign": "伊利诺伊大学厄巴纳-香槟分校",
  "University of Maryland Global Campus": "马里兰大学全球校区",
  "University of Michigan-Ann Arbor": "密歇根大学安娜堡分校",
  "University of North Texas": "北得克萨斯大学",
  "University of Phoenix-Arizona": "凤凰城大学",
  "University of South Florida": "南佛罗里达大学",
  "University of Wisconsin-Madison": "威斯康星大学麦迪逊分校",
  "Western Governors University": "西部州长大学",
};

export function getStudyAbroadUniversityNameZh(name: string) {
  return UNIVERSITY_NAME_ZH_MAP[String(name || "").trim()] || "";
}
