export type StudyAbroadProgram = {
  id: string;
  country: string;
  city: string;
  schoolName: string;
  programName: string;
  degree: "硕士" | "MBA";
  discipline: string;
  summary: string;
  duration?: string;
  intake?: string;
  keywords: string[];
  tags: string[];
  overviewUrl: string;
  admissionsUrl?: string;
  checkedAt: string;
  priority: number;
};

export const STUDY_ABROAD_DATA_UPDATED_AT = "2026-04-24";

export const POPULAR_MAJOR_HINTS = [
  "计算机 / AI",
  "金融",
  "商科 / 管理",
  "市场营销 / 传媒",
  "教育",
  "商业分析 / 数据",
] as const;

export const MAJOR_FAMILIES: Record<string, string[]> = {
  "计算机 / AI": [
    "计算机",
    "computer science",
    "cs",
    "software",
    "programming",
    "ai",
    "人工智能",
    "machine learning",
    "cybersecurity",
    "information technology",
    "it",
    "ux",
    "hci",
    "数据科学",
  ],
  金融: [
    "金融",
    "finance",
    "investment",
    "banking",
    "wealth",
    "risk",
    "quant",
    "fintech",
  ],
  "商科 / 管理": [
    "商科",
    "business",
    "management",
    "commerce",
    "mba",
    "strategy",
    "consulting",
    "商业分析",
  ],
  "市场营销 / 传媒": [
    "市场",
    "营销",
    "marketing",
    "communications",
    "advertising",
    "media",
    "brand",
    "imc",
    "传媒",
  ],
  教育: ["教育", "education", "teaching", "policy", "pedagogy", "research"],
  "商业分析 / 数据": [
    "数据",
    "data",
    "analytics",
    "analysis",
    "business analytics",
    "sql",
    "python",
    "information systems",
  ],
};

export const STUDY_ABROAD_PROGRAMS: StudyAbroadProgram[] = [
  {
    id: "cmu-mscs",
    country: "美国",
    city: "Pittsburgh",
    schoolName: "Carnegie Mellon University",
    programName: "M.S. in Computer Science",
    degree: "硕士",
    discipline: "计算机科学",
    summary:
      "CMU 计算机系官网显示，该项目面向具备数学、编程和逻辑基础的申请者，课程可在导师指导下灵活组合，研究为可选项。",
    duration: "3 学期",
    intake: "秋季",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "人工智能",
      "ai",
      "软件",
      "算法",
      "programming",
      "machine learning",
    ],
    tags: ["计算机", "AI", "软件", "研究可选"],
    overviewUrl:
      "https://www.csd.cmu.edu/academics/masters/ms-in-computer-science",
    admissionsUrl: "https://csd.cs.cmu.edu/academics/masters/admissions",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 100,
  },
  {
    id: "columbia-mba",
    country: "美国",
    city: "New York",
    schoolName: "Columbia Business School",
    programName: "Full-Time MBA",
    degree: "MBA",
    discipline: "商科 / 管理",
    summary:
      "哥大商学院官网显示，Full-Time MBA 依托纽约产业资源，提供 August Entry 与 January Entry 两种路径，适合希望在金融、咨询、管理等方向发展的申请者。",
    duration: "16-20 个月",
    intake: "1 月 / 8 月",
    keywords: [
      "商科",
      "管理",
      "business",
      "management",
      "mba",
      "金融",
      "咨询",
      "leadership",
    ],
    tags: ["MBA", "管理", "金融", "纽约"],
    overviewUrl: "https://academics.business.columbia.edu/mba",
    admissionsUrl: "https://academics.business.columbia.edu/admissions/mba",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 92,
  },
  {
    id: "northwestern-imc",
    country: "美国",
    city: "Evanston / Chicago",
    schoolName: "Northwestern University",
    programName: "M.S. in Integrated Marketing Communications",
    degree: "硕士",
    discipline: "市场营销 / 传媒",
    summary:
      "Medill 官网显示，IMC Full-Time 项目为 12 个月，强调以客户为中心的营销传播框架，兼顾数据分析、品牌叙事和真实客户项目。",
    duration: "12 个月",
    intake: "秋季",
    keywords: [
      "市场营销",
      "营销",
      "传媒",
      "communications",
      "marketing",
      "media",
      "advertising",
      "brand",
      "imc",
    ],
    tags: ["营销", "传媒", "品牌", "数据叙事"],
    overviewUrl: "https://www.medill.northwestern.edu/imc/full-time/",
    admissionsUrl:
      "https://www.medill.northwestern.edu/imc/full-time/admissions/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 86,
  },
  {
    id: "ucl-cs",
    country: "英国",
    city: "London",
    schoolName: "University College London",
    programName: "Computer Science MSc",
    degree: "硕士",
    discipline: "计算机科学",
    summary:
      "UCL 官网显示，该项目覆盖编程、App Engineering、计算机体系结构、操作系统、算法和数据库，并包含产业或研究项目。",
    duration: "1 年",
    intake: "秋季",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "软件",
      "programming",
      "machine learning",
      "信息技术",
      "it",
    ],
    tags: ["计算机", "软件", "项目制", "伦敦"],
    overviewUrl:
      "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/computer-science-msc",
    admissionsUrl:
      "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/computer-science-msc",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 93,
  },
  {
    id: "lse-finance",
    country: "英国",
    city: "London",
    schoolName: "London School of Economics and Political Science",
    programName: "MSc Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "LSE 官网将该项目定义为广义金融硕士，先打牢 corporate finance 与 financial markets 基础，再通过选修课延展到更细分方向。",
    duration: "1 年",
    intake: "秋季",
    keywords: [
      "金融",
      "finance",
      "investment",
      "banking",
      "asset management",
      "corporate finance",
      "风险",
    ],
    tags: ["金融", "投行", "资产管理", "伦敦"],
    overviewUrl: "https://www.lse.ac.uk/study-at-lse/graduate/msc-finance-full-time",
    admissionsUrl: "https://www.lse.ac.uk/study-at-lse/graduate/msc-finance-full-time",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 91,
  },
  {
    id: "edinburgh-education",
    country: "英国",
    city: "Edinburgh",
    schoolName: "The University of Edinburgh",
    programName: "Education MSc",
    degree: "硕士",
    discipline: "教育",
    summary:
      "爱丁堡官网显示，Education MSc 是 Moray House 的旗舰授课型项目，适合希望进入教育政策、研究或实践领域的申请者，也可按方向细分路径。",
    duration: "1 年",
    keywords: [
      "教育",
      "education",
      "teaching",
      "policy",
      "research",
      "教育政策",
      "pedagogy",
    ],
    tags: ["教育", "政策", "研究", "苏格兰"],
    overviewUrl: "https://study.ed.ac.uk/programmes/postgraduate-taught/98-education",
    admissionsUrl: "https://study.ed.ac.uk/programmes/postgraduate-taught/98-education",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 82,
  },
  {
    id: "toronto-mi",
    country: "加拿大",
    city: "Toronto",
    schoolName: "University of Toronto",
    programName: "Master of Information",
    degree: "硕士",
    discipline: "信息 / UX / 数据",
    summary:
      "多伦多大学官网显示，MI 是两年制职业硕士，包含 Human-Centered Data Science、User Experience Design、Information Systems & Design 等多个 concentration。",
    duration: "2 年",
    intake: "秋季",
    keywords: [
      "信息",
      "ux",
      "user experience",
      "data science",
      "human centered data science",
      "information systems",
      "design",
      "hci",
    ],
    tags: ["UX", "数据", "信息系统", "设计"],
    overviewUrl: "https://www.sgs.utoronto.ca/programs/information/",
    admissionsUrl:
      "https://www.sgs.utoronto.ca/future-students/admission-application-requirements/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 84,
  },
  {
    id: "ubc-mban",
    country: "加拿大",
    city: "Vancouver",
    schoolName: "The University of British Columbia",
    programName: "Master of Business Analytics",
    degree: "硕士",
    discipline: "商业分析 / 数据",
    summary:
      "UBC Sauder 官网显示，MBAN 为 12 个月项目，强调将数据转化为可执行商业洞察，并配有 internship、consulting project 或 research project。",
    duration: "12 个月",
    keywords: [
      "商业分析",
      "business analytics",
      "analytics",
      "data",
      "数据",
      "sql",
      "python",
      "strategy",
    ],
    tags: ["商业分析", "数据", "实战项目", "温哥华"],
    overviewUrl: "https://org-www.sauder.ubc.ca/programs/masters-degrees/mban",
    admissionsUrl:
      "https://www.grad.ubc.ca/prospective-students/graduate-degree-programs/Master-of-business-analytics",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 88,
  },
  {
    id: "melbourne-mit",
    country: "澳大利亚",
    city: "Melbourne",
    schoolName: "The University of Melbourne",
    programName: "Master of Information Technology",
    degree: "硕士",
    discipline: "信息技术 / AI",
    summary:
      "墨尔本大学官网显示，MIT 提供 Computing、Cybersecurity、Distributed Computing、Human-Computer Interaction、Artificial Intelligence 等方向，并包含 industry-based learning。",
    duration: "2 年",
    intake: "3 月 / 7 月",
    keywords: [
      "信息技术",
      "it",
      "计算机",
      "artificial intelligence",
      "人工智能",
      "cybersecurity",
      "hci",
      "distributed computing",
    ],
    tags: ["IT", "AI", "HCI", "澳洲八大"],
    overviewUrl:
      "https://study.unimelb.edu.au/find/courses/graduate/master-of-information-technology",
    admissionsUrl:
      "https://study.unimelb.edu.au/find/courses/graduate/master-of-information-technology/entry-requirements",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 87,
  },
  {
    id: "unsw-commerce",
    country: "澳大利亚",
    city: "Sydney",
    schoolName: "UNSW Sydney",
    programName: "Master of Commerce",
    degree: "硕士",
    discipline: "商科 / 金融 / 管理",
    summary:
      "UNSW 官网显示，Master of Commerce 为 1.7 年全日制项目，可在 Finance、Marketing、Business Analytics 等方向中组合专长，课程强调行业实践。",
    duration: "1.7 年",
    keywords: [
      "商科",
      "commerce",
      "金融",
      "finance",
      "marketing",
      "business analytics",
      "management",
      "strategy",
    ],
    tags: ["商科", "金融", "营销", "悉尼"],
    overviewUrl:
      "https://www.unsw.edu.au/study/postgraduate/master-of-commerce?studentType=international",
    admissionsUrl:
      "https://www.unsw.edu.au/study/postgraduate/master-of-commerce?studentType=international",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 78,
  },
  {
    id: "hku-mscs",
    country: "中国香港",
    city: "Hong Kong",
    schoolName: "The University of Hong Kong",
    programName: "Master of Science in Computer Science",
    degree: "硕士",
    discipline: "计算机科学",
    summary:
      "HKU 官网显示，该项目提供 applied 与 fundamental 两类课程，也可进入更加聚焦的 ICT stream，适合希望系统进阶计算机方向的申请者。",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "ai",
      "人工智能",
      "ict",
      "software",
      "data",
    ],
    tags: ["计算机", "港校", "ICT", "AI"],
    overviewUrl: "https://www.msc-cs.hku.hk/",
    admissionsUrl: "https://www.msc-cs.hku.hk/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 89,
  },
  {
    id: "hkust-mfin",
    country: "中国香港",
    city: "Hong Kong",
    schoolName: "The Hong Kong University of Science and Technology",
    programName: "MSc in Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "HKUST 官网将 MSc in Finance 定位为理论与实践并重的金融硕士，强调专业课程训练与行业联系，适合想进入金融相关岗位的学生。",
    keywords: [
      "金融",
      "finance",
      "investment",
      "risk",
      "banking",
      "asset management",
      "fintech",
    ],
    tags: ["金融", "港校", "实务导向", "商学院"],
    overviewUrl: "https://mfin.hkust.edu.hk/",
    admissionsUrl: "https://mfin.hkust.edu.hk/admissions/admissions-requirement",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 90,
  },
  {
    id: "cuhk-marketing",
    country: "中国香港",
    city: "Hong Kong",
    schoolName: "The Chinese University of Hong Kong",
    programName: "MSc in Marketing",
    degree: "硕士",
    discipline: "市场营销",
    summary:
      "CUHK 官网显示，MSc in Marketing 同时覆盖品牌、公关与国际营销，也提供 AI and Quantitative Marketing 路径，适合传统营销与数字营销双向发展。",
    keywords: [
      "市场营销",
      "marketing",
      "传媒",
      "communications",
      "brand",
      "广告",
      "ai marketing",
      "quantitative marketing",
    ],
    tags: ["市场", "品牌", "AI 营销", "港校"],
    overviewUrl: "https://masters.bschool.cuhk.edu.hk/programmes/mscmkt/",
    admissionsUrl:
      "https://masters.bschool.cuhk.edu.hk/programmes/mscmkt/admissions/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 83,
  },
  {
    id: "nus-mcomp-cs",
    country: "新加坡",
    city: "Singapore",
    schoolName: "National University of Singapore",
    programName: "Master of Computing (Computer Science Specialisation)",
    degree: "硕士",
    discipline: "计算机 / AI",
    summary:
      "NUS 官网显示，MComp CS 让学生深入计算机核心领域与前沿研究，适合希望夯实技术深度并面向 IT 职业进阶的申请者。",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "ai",
      "人工智能",
      "it",
      "software",
      "computing",
    ],
    tags: ["计算机", "新加坡", "技术深度", "School of Computing"],
    overviewUrl:
      "https://masters.nus.edu.sg/programmes/master-of-computing/mcomp---computer-science-specialisation",
    admissionsUrl:
      "https://masters.nus.edu.sg/programmes/master-of-computing",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 94,
  },
  {
    id: "smu-applied-finance",
    country: "新加坡",
    city: "Singapore",
    schoolName: "Singapore Management University",
    programName: "MSc in Applied Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "SMU 官网显示，MAF 聚焦国际与本土金融市场的原理、实践与运作，fresh graduates 也可申请，课程覆盖 financial analytics、sustainable finance 等模块。",
    duration: "18 个月",
    intake: "8 月",
    keywords: [
      "金融",
      "finance",
      "financial analytics",
      "investment",
      "wealth management",
      "sustainable finance",
      "banking",
    ],
    tags: ["金融", "新加坡", "应用导向", "分析"],
    overviewUrl: "https://masters.smu.edu.sg/programme/msc-in-applied-finance",
    admissionsUrl: "https://masters.smu.edu.sg/programme/msc-in-applied-finance",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 85,
  },
];

export const STUDY_ABROAD_COUNTRIES = Array.from(
  new Set(STUDY_ABROAD_PROGRAMS.map((program) => program.country))
);
