export type StudyAbroadProgram = {
  id: string;
  country: string;
  city: string;
  schoolName: string;
  programName: string;
  degree: "本科" | "硕士" | "博士";
  discipline: string;
  summary: string;
  duration?: string;
  intake?: string;
  keywords: string[];
  tags: string[];
  overviewUrl: string;
  admissionsUrl?: string;
  checkedAt: string;
  priority: number;
};

export const STUDY_ABROAD_DATA_UPDATED_AT = "2026-04-24";

export const STUDY_ABROAD_MAJOR_GROUPS = [
  {
    label: "理工与数据",
    options: [
      "计算机 / AI",
      "商业分析 / 数据",
      "数学 / 统计",
      "机械 / 电子 / 工程",
      "环境 / 可持续",
    ],
  },
  {
    label: "商科与社科",
    options: [
      "金融",
      "会计",
      "经济学",
      "商科 / 管理",
      "MBA",
      "市场营销 / 传媒",
      "法学",
      "公共政策 / 国际关系",
      "社会学 / 社工",
      "心理学",
    ],
  },
  {
    label: "教育与人文",
    options: ["教育", "语言 / 文学"],
  },
  {
    label: "生命与健康",
    options: ["生物 / 生物医学", "公共卫生"],
  },
  {
    label: "设计与空间",
    options: ["建筑 / 城市规划", "设计 / 艺术"],
  },
] as const;

export const STUDY_ABROAD_MAJOR_OPTIONS = STUDY_ABROAD_MAJOR_GROUPS.flatMap(
  (group) => group.options
);

export const STUDY_ABROAD_MAJOR_SPECIALIZATIONS: Record<string, string[]> = {
  "计算机 / AI": [
    "人工智能",
    "计算机科学",
    "数据科学",
    "人机交互",
    "网络安全",
    "软件工程",
  ],
  "商业分析 / 数据": [
    "商业分析",
    "数据分析",
    "信息系统",
    "供应链分析",
    "金融科技",
  ],
  "数学 / 统计": ["统计学", "应用数学", "生物统计", "精算", "运筹学"],
  "机械 / 电子 / 工程": [
    "机械工程",
    "电子电气工程",
    "计算机工程",
    "土木工程",
    "工业工程",
    "材料工程",
  ],
  "环境 / 可持续": [
    "环境科学",
    "可持续发展",
    "环境工程",
    "能源系统",
    "气候政策",
  ],
  金融: ["金融学", "金融工程", "量化金融", "投资管理", "风险管理", "金融科技"],
  会计: ["会计", "税务", "审计", "管理会计"],
  经济学: ["经济学", "应用经济学", "计量经济学", "发展经济学"],
  "商科 / 管理": ["管理学", "国际商务", "供应链管理", "创业与战略", "组织管理"],
  MBA: ["全日制 MBA", "EMBA", "科技管理 MBA", "金融 MBA", "市场管理 MBA"],
  "市场营销 / 传媒": [
    "市场营销",
    "整合营销传播",
    "传媒",
    "广告与品牌",
    "数字媒体",
  ],
  法学: ["国际法", "商法", "知识产权", "仲裁与争端解决", "法学硕士 LLM"],
  "公共政策 / 国际关系": [
    "公共政策",
    "公共管理",
    "国际关系",
    "国际事务",
    "全球治理",
  ],
  "社会学 / 社工": ["社会学", "社会工作", "社会政策", "社区发展"],
  心理学: ["临床心理", "咨询心理", "发展心理", "行为科学", "教育心理"],
  教育: ["教育学", "教育政策", "TESOL", "课程与教学", "高等教育"],
  "语言 / 文学": ["语言学", "英语文学", "翻译", "比较文学", "对外英语教学"],
  "生物 / 生物医学": ["生物学", "生物医学", "生物技术", "神经科学", "分子生物学"],
  公共卫生: ["流行病学", "全球公共卫生", "卫生政策", "卫生管理", "环境健康"],
  "建筑 / 城市规划": ["建筑学", "城市规划", "城市设计", "景观建筑", "房地产开发"],
  "设计 / 艺术": ["视觉传达", "交互设计", "工业设计", "纯艺术", "服务设计"],
};

export const STUDY_ABROAD_SPECIALIZATION_OPTIONS = Object.values(
  STUDY_ABROAD_MAJOR_SPECIALIZATIONS
).flat();

export const POPULAR_MAJOR_HINTS = STUDY_ABROAD_MAJOR_OPTIONS;

export const MAJOR_FAMILIES: Record<string, string[]> = {
  "计算机 / AI": [
    "计算机",
    "计算机科学",
    "computer science",
    "cs",
    "软件工程",
    "software",
    "programming",
    "ai",
    "人工智能",
    "machine learning",
    "cybersecurity",
    "information technology",
    "it",
    "ux",
    "hci",
    "人机交互",
    "交互设计",
    "数据科学",
  ],
  金融: [
    "金融",
    "金融学",
    "finance",
    "master of finance",
    "mfin",
    "msf",
    "financial engineering",
    "mfe",
    "金融工程",
    "量化金融",
    "金工",
    "investment",
    "banking",
    "wealth",
    "risk",
    "quant",
    "fintech",
  ],
  "商科 / 管理": [
    "商科",
    "business",
    "management",
    "commerce",
    "strategy",
    "consulting",
    "商业分析",
  ],
  MBA: [
    "mba",
    "master of business administration",
    "business administration",
    "executive mba",
    "full time mba",
    "工商管理",
  ],
  "市场营销 / 传媒": [
    "市场",
    "营销",
    "marketing",
    "communications",
    "advertising",
    "media",
    "brand",
    "imc",
    "传媒",
  ],
  教育: ["教育", "education", "teaching", "policy", "pedagogy", "research"],
  "数学 / 统计": [
    "数学",
    "mathematics",
    "statistics",
    "applied mathematics",
    "statistical",
    "biostatistics",
    "probability",
  ],
  会计: [
    "会计",
    "accounting",
    "msa",
    "master of accounting",
    "taxation",
    "audit",
  ],
  经济学: [
    "经济学",
    "economics",
    "applied economics",
    "economic policy",
    "econometrics",
  ],
  心理学: [
    "心理学",
    "psychology",
    "clinical psychology",
    "counseling psychology",
    "behavioral science",
    "mental health",
  ],
  "商业分析 / 数据": [
    "数据",
    "data",
    "analytics",
    "analysis",
    "business analytics",
    "商业分析",
    "sql",
    "python",
    "information systems",
  ],
  法学: [
    "法学",
    "law",
    "legal studies",
    "jurisprudence",
    "llm",
    "international law",
  ],
  "公共政策 / 国际关系": [
    "公共政策",
    "public policy",
    "public administration",
    "international relations",
    "international affairs",
    "global affairs",
    "外交",
  ],
  "社会学 / 社工": [
    "社会学",
    "sociology",
    "social work",
    "social policy",
    "community",
    "social justice",
  ],
  "公共卫生": [
    "公共卫生",
    "public health",
    "epidemiology",
    "global health",
    "health policy",
    "health administration",
  ],
  "生物 / 生物医学": [
    "生物",
    "biology",
    "biomedical",
    "biotechnology",
    "genetics",
    "neuroscience",
    "molecular",
    "microbiology",
  ],
  "机械 / 电子 / 工程": [
    "工程",
    "engineering",
    "mechanical engineering",
    "electrical engineering",
    "computer engineering",
    "civil engineering",
    "industrial engineering",
    "materials engineering",
  ],
  "建筑 / 城市规划": [
    "建筑",
    "architecture",
    "urban planning",
    "city planning",
    "urban design",
    "regional planning",
    "landscape architecture",
  ],
  "设计 / 艺术": [
    "设计",
    "design",
    "art",
    "fine arts",
    "visual arts",
    "interaction design",
    "industrial design",
  ],
  "环境 / 可持续": [
    "环境",
    "environment",
    "sustainability",
    "climate",
    "ecology",
    "environmental science",
    "environmental policy",
  ],
  "语言 / 文学": [
    "语言",
    "linguistics",
    "literature",
    "english",
    "translation",
    "comparative literature",
    "tesol",
  ],
};

export const COUNTRY_QUERY_ALIASES: Record<string, string[]> = {
  美国: ["美国", "United States", "US", "USA", "America"],
  英国: ["英国", "United Kingdom", "UK", "Britain"],
  加拿大: ["加拿大", "Canada"],
  澳大利亚: ["澳大利亚", "Australia", "AU"],
  中国香港: ["中国香港", "香港", "Hong Kong", "HK"],
  新加坡: ["新加坡", "Singapore", "SG"],
};

export const DEGREE_QUERY_ALIASES: Record<string, string[]> = {
  本科: ["本科", "bachelor", "undergraduate", "ba", "bs", "bsc", "beng"],
  硕士: [
    "硕士",
    "master",
    "masters",
    "graduate",
    "MS",
    "MSc",
    "MA",
    "master of science",
    "master of arts",
    "MFin",
    "MSF",
    "MFE",
  ],
  博士: ["博士", "phd", "doctor", "doctoral", "dphil"],
};

export const MAJOR_QUERY_ALIASES: Record<string, string[]> = {
  "计算机 / AI": [
    "计算机",
    "computer science",
    "artificial intelligence",
    "software engineering",
    "machine learning",
    "human computer interaction",
  ],
  金融: [
    "金融",
    "finance",
    "master of finance",
    "financial engineering",
    "quantitative finance",
    "fintech",
  ],
  "商科 / 管理": [
    "商科",
    "business",
    "management",
    "commerce",
    "business analytics",
  ],
  MBA: [
    "mba",
    "master of business administration",
    "business administration",
    "full time mba",
    "executive mba",
  ],
  "市场营销 / 传媒": [
    "市场营销",
    "marketing",
    "communications",
    "media",
    "brand management",
  ],
  教育: ["教育", "education", "education policy", "teaching"],
  "数学 / 统计": [
    "数学",
    "statistics",
    "mathematics",
    "applied mathematics",
    "biostatistics",
  ],
  会计: ["会计", "accounting", "master of accounting", "taxation", "audit"],
  经济学: ["经济学", "economics", "applied economics", "econometrics"],
  心理学: [
    "心理学",
    "psychology",
    "clinical psychology",
    "counseling psychology",
    "behavioral science",
    "mental health",
  ],
  "商业分析 / 数据": [
    "商业分析",
    "business analytics",
    "data analytics",
    "information systems",
  ],
  法学: ["法学", "law", "llm", "legal studies", "international law"],
  "公共政策 / 国际关系": [
    "公共政策",
    "public policy",
    "public administration",
    "international relations",
    "international affairs",
  ],
  "社会学 / 社工": ["社会学", "sociology", "social work", "social policy"],
  公共卫生: [
    "公共卫生",
    "public health",
    "epidemiology",
    "global health",
    "health policy",
  ],
  "生物 / 生物医学": [
    "生物",
    "biology",
    "biomedical",
    "biotechnology",
    "neuroscience",
  ],
  "机械 / 电子 / 工程": [
    "工程",
    "engineering",
    "mechanical engineering",
    "electrical engineering",
    "computer engineering",
    "civil engineering",
  ],
  "建筑 / 城市规划": [
    "建筑",
    "architecture",
    "urban planning",
    "urban design",
    "landscape architecture",
  ],
  "设计 / 艺术": ["设计", "design", "art", "fine arts", "visual arts"],
  "环境 / 可持续": [
    "环境",
    "environment",
    "sustainability",
    "climate",
    "environmental science",
  ],
  "语言 / 文学": [
    "语言",
    "linguistics",
    "literature",
    "translation",
    "tesol",
    "comparative literature",
  ],
};

export const SPECIALIZATION_QUERY_ALIASES: Record<string, string[]> = {
  人工智能: ["人工智能", "artificial intelligence", "ai", "machine learning"],
  计算机科学: ["计算机科学", "computer science", "cs"],
  数据科学: ["数据科学", "data science", "machine learning", "analytics"],
  人机交互: ["人机交互", "human computer interaction", "hci", "interaction design"],
  网络安全: ["网络安全", "cybersecurity", "information security", "security"],
  软件工程: ["软件工程", "software engineering", "software development"],
  商业分析: ["商业分析", "business analytics", "business analysis"],
  数据分析: ["数据分析", "data analytics", "analytics", "data analysis"],
  信息系统: ["信息系统", "information systems", "mis"],
  供应链分析: ["供应链分析", "supply chain analytics", "operations analytics"],
  金融科技: ["金融科技", "fintech", "financial technology"],
  统计学: ["统计学", "statistics", "statistical science"],
  应用数学: ["应用数学", "applied mathematics", "applied math"],
  生物统计: ["生物统计", "biostatistics", "bio statistics"],
  精算: ["精算", "actuarial science", "actuarial"],
  运筹学: ["运筹学", "operations research", "or"],
  机械工程: ["机械工程", "mechanical engineering"],
  电子电气工程: ["电子电气工程", "electrical engineering", "electronic engineering"],
  计算机工程: ["计算机工程", "computer engineering"],
  土木工程: ["土木工程", "civil engineering"],
  工业工程: ["工业工程", "industrial engineering"],
  材料工程: ["材料工程", "materials engineering", "material science"],
  环境科学: ["环境科学", "environmental science"],
  可持续发展: ["可持续发展", "sustainability", "sustainable development"],
  环境工程: ["环境工程", "environmental engineering"],
  能源系统: ["能源系统", "energy systems", "energy"],
  气候政策: ["气候政策", "climate policy", "climate"],
  金融学: ["金融学", "finance", "master of finance", "mfin"],
  金融工程: ["金融工程", "financial engineering", "mfe"],
  量化金融: ["量化金融", "quantitative finance", "quant finance"],
  投资管理: ["投资管理", "investment management", "asset management"],
  风险管理: ["风险管理", "risk management"],
  会计: ["会计", "accounting", "master of accounting", "msa"],
  税务: ["税务", "taxation", "tax"],
  审计: ["审计", "audit", "auditing"],
  管理会计: ["管理会计", "managerial accounting", "management accounting"],
  经济学: ["经济学", "economics"],
  应用经济学: ["应用经济学", "applied economics"],
  计量经济学: ["计量经济学", "econometrics"],
  发展经济学: ["发展经济学", "development economics"],
  管理学: ["管理学", "management"],
  国际商务: ["国际商务", "international business"],
  供应链管理: ["供应链管理", "supply chain management"],
  "创业与战略": ["创业", "entrepreneurship", "strategy", "strategic management"],
  组织管理: ["组织管理", "organizational management", "organization"],
  "全日制 MBA": ["全日制 mba", "full time mba", "full-time mba"],
  EMBA: ["emba", "executive mba"],
  "科技管理 MBA": ["科技管理 mba", "technology mba", "tech mba"],
  "金融 MBA": ["金融 mba", "finance mba"],
  "市场管理 MBA": ["市场管理 mba", "marketing mba"],
  市场营销: ["市场营销", "marketing"],
  整合营销传播: ["整合营销传播", "integrated marketing communications", "imc"],
  传媒: ["传媒", "media", "communications"],
  "广告与品牌": ["广告与品牌", "advertising", "brand management", "branding"],
  数字媒体: ["数字媒体", "digital media"],
  国际法: ["国际法", "international law"],
  商法: ["商法", "business law", "commercial law"],
  知识产权: ["知识产权", "intellectual property", "ip law"],
  仲裁与争端解决: ["仲裁", "arbitration", "dispute resolution"],
  "法学硕士 LLM": ["法学硕士", "llm", "master of laws"],
  公共政策: ["公共政策", "public policy"],
  公共管理: ["公共管理", "public administration", "mpa"],
  国际关系: ["国际关系", "international relations"],
  国际事务: ["国际事务", "international affairs"],
  全球治理: ["全球治理", "global governance"],
  社会学: ["社会学", "sociology"],
  社会工作: ["社会工作", "social work"],
  社会政策: ["社会政策", "social policy"],
  社区发展: ["社区发展", "community development"],
  临床心理: ["临床心理", "clinical psychology"],
  咨询心理: ["咨询心理", "counseling psychology"],
  发展心理: ["发展心理", "developmental psychology"],
  行为科学: ["行为科学", "behavioral science"],
  教育心理: ["教育心理", "educational psychology"],
  教育学: ["教育学", "education"],
  教育政策: ["教育政策", "education policy"],
  TESOL: ["tesol", "teaching english to speakers of other languages"],
  课程与教学: ["课程与教学", "curriculum and instruction"],
  高等教育: ["高等教育", "higher education"],
  语言学: ["语言学", "linguistics"],
  英语文学: ["英语文学", "english literature", "literature"],
  翻译: ["翻译", "translation", "interpreting"],
  比较文学: ["比较文学", "comparative literature"],
  对外英语教学: ["对外英语教学", "tesol", "applied linguistics"],
  生物学: ["生物学", "biology"],
  生物医学: ["生物医学", "biomedical", "biomedical science"],
  生物技术: ["生物技术", "biotechnology"],
  神经科学: ["神经科学", "neuroscience"],
  分子生物学: ["分子生物学", "molecular biology"],
  流行病学: ["流行病学", "epidemiology"],
  全球公共卫生: ["全球公共卫生", "global public health", "global health"],
  卫生政策: ["卫生政策", "health policy"],
  卫生管理: ["卫生管理", "health administration"],
  环境健康: ["环境健康", "environmental health"],
  建筑学: ["建筑学", "architecture"],
  城市规划: ["城市规划", "urban planning", "city planning"],
  城市设计: ["城市设计", "urban design"],
  景观建筑: ["景观建筑", "landscape architecture"],
  房地产开发: ["房地产开发", "real estate development"],
  视觉传达: ["视觉传达", "visual communication", "graphic design"],
  交互设计: ["交互设计", "interaction design", "ux design"],
  工业设计: ["工业设计", "industrial design"],
  纯艺术: ["纯艺术", "fine arts"],
  服务设计: ["服务设计", "service design"],
};

export const STUDY_ABROAD_PROGRAMS: StudyAbroadProgram[] = [
  {
    id: "cmu-mscs",
    country: "美国",
    city: "Pittsburgh",
    schoolName: "Carnegie Mellon University",
    programName: "M.S. in Computer Science",
    degree: "硕士",
    discipline: "计算机科学",
    summary:
      "CMU 计算机系官网显示，该项目面向具备数学、编程和逻辑基础的申请者，课程可在导师指导下灵活组合，研究为可选项。",
    duration: "3 学期",
    intake: "秋季",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "人工智能",
      "ai",
      "软件",
      "算法",
      "programming",
      "machine learning",
    ],
    tags: ["计算机", "AI", "软件", "研究可选"],
    overviewUrl:
      "https://www.csd.cmu.edu/academics/masters/ms-in-computer-science",
    admissionsUrl: "https://csd.cs.cmu.edu/academics/masters/admissions",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 100,
  },
  {
    id: "mit-mfin",
    country: "美国",
    city: "Cambridge",
    schoolName: "Massachusetts Institute of Technology",
    programName: "Master of Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "MIT Sloan 官网显示，MFin 面向对金融有明确兴趣的高潜申请者，既欢迎金融背景学生，也欢迎工程、数学、物理和计算机等高量化背景申请者。",
    duration: "12-18 个月",
    intake: "秋季",
    keywords: [
      "金融",
      "finance",
      "master of finance",
      "mfin",
      "investment",
      "banking",
      "quant",
      "fintech",
    ],
    tags: ["金融", "量化", "MIT Sloan", "波士顿"],
    overviewUrl: "https://mitsloan.mit.edu/mfin/admissions",
    admissionsUrl: "https://mitsloan.mit.edu/mfin/admissions",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 97,
  },
  {
    id: "princeton-mfin",
    country: "美国",
    city: "Princeton",
    schoolName: "Princeton University",
    programName: "Master in Finance",
    degree: "硕士",
    discipline: "金融 / 金融工程",
    summary:
      "普林斯顿官网显示，Master in Finance 覆盖金融工程、风险管理、量化资管、宏观金融预测、量化交易和应用研究，项目竞争非常激烈。",
    duration: "2 年",
    intake: "秋季",
    keywords: [
      "金融",
      "finance",
      "master in finance",
      "financial engineering",
      "risk management",
      "quantitative trading",
      "asset management",
      "quant",
    ],
    tags: ["金融", "金融工程", "量化", "常春藤"],
    overviewUrl:
      "https://bcf.princeton.edu/academic-programs/master-in-finance/apply-for-the-master-in-finance-program/",
    admissionsUrl:
      "https://bcf.princeton.edu/academic-programs/master-in-finance/apply-for-the-master-in-finance-program/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 96,
  },
  {
    id: "berkeley-mfe",
    country: "美国",
    city: "Berkeley",
    schoolName: "University of California, Berkeley",
    programName: "Master of Financial Engineering",
    degree: "硕士",
    discipline: "金融工程 / 量化金融",
    summary:
      "Berkeley Haas 官网显示，MFE 是一到两年的项目，面向金融、经济、统计、数学、工程和计算机等量化背景申请者，春季入学。",
    duration: "1-2 年",
    intake: "春季",
    keywords: [
      "金融工程",
      "financial engineering",
      "mfe",
      "quantitative finance",
      "金融",
      "finance",
      "statistics",
      "computer science",
    ],
    tags: ["金融工程", "量化", "STEM", "加州"],
    overviewUrl: "https://mfe.haas.berkeley.edu/admissions",
    admissionsUrl: "https://mfe.haas.berkeley.edu/admissions/requirements",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 95,
  },
  {
    id: "usc-msf",
    country: "美国",
    city: "Los Angeles",
    schoolName: "University of Southern California",
    programName: "Master of Science in Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "USC Marshall 官网显示，MSF 为 16 个月 STEM 项目，强调 valuation、portfolio management、risk modeling 等能力，也覆盖 fintech、房地产金融等方向。",
    duration: "16 个月",
    intake: "秋季",
    keywords: [
      "金融",
      "finance",
      "master of science in finance",
      "msf",
      "valuation",
      "portfolio management",
      "risk modeling",
      "fintech",
    ],
    tags: ["金融", "STEM", "实务导向", "洛杉矶"],
    overviewUrl: "https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-finance",
    admissionsUrl:
      "https://www.marshall.usc.edu/programs/graduate-programs/specialized-masters/ms-finance/admissions",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 90,
  },
  {
    id: "columbia-mba",
    country: "美国",
    city: "New York",
    schoolName: "Columbia Business School",
    programName: "Full-Time MBA",
    degree: "硕士",
    discipline: "MBA",
    summary:
      "哥大商学院官网显示，Full-Time MBA 依托纽约产业资源，提供 August Entry 与 January Entry 两种路径，适合希望在金融、咨询、管理等方向发展的申请者。",
    duration: "16-20 个月",
    intake: "1 月 / 8 月",
    keywords: [
      "商科",
      "管理",
      "business",
      "management",
      "mba",
      "金融",
      "咨询",
      "leadership",
    ],
    tags: ["MBA", "管理", "金融", "纽约"],
    overviewUrl: "https://academics.business.columbia.edu/mba",
    admissionsUrl: "https://academics.business.columbia.edu/admissions/mba",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 92,
  },
  {
    id: "northwestern-imc",
    country: "美国",
    city: "Evanston / Chicago",
    schoolName: "Northwestern University",
    programName: "M.S. in Integrated Marketing Communications",
    degree: "硕士",
    discipline: "市场营销 / 传媒",
    summary:
      "Medill 官网显示，IMC Full-Time 项目为 12 个月，强调以客户为中心的营销传播框架，兼顾数据分析、品牌叙事和真实客户项目。",
    duration: "12 个月",
    intake: "秋季",
    keywords: [
      "市场营销",
      "营销",
      "传媒",
      "communications",
      "marketing",
      "media",
      "advertising",
      "brand",
      "imc",
    ],
    tags: ["营销", "传媒", "品牌", "数据叙事"],
    overviewUrl: "https://www.medill.northwestern.edu/imc/full-time/",
    admissionsUrl:
      "https://www.medill.northwestern.edu/imc/full-time/admissions/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 86,
  },
  {
    id: "ucl-cs",
    country: "英国",
    city: "London",
    schoolName: "University College London",
    programName: "Computer Science MSc",
    degree: "硕士",
    discipline: "计算机科学",
    summary:
      "UCL 官网显示，该项目覆盖编程、App Engineering、计算机体系结构、操作系统、算法和数据库，并包含产业或研究项目。",
    duration: "1 年",
    intake: "秋季",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "软件",
      "programming",
      "machine learning",
      "信息技术",
      "it",
    ],
    tags: ["计算机", "软件", "项目制", "伦敦"],
    overviewUrl:
      "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/computer-science-msc",
    admissionsUrl:
      "https://www.ucl.ac.uk/prospective-students/graduate/taught-degrees/computer-science-msc",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 93,
  },
  {
    id: "lse-finance",
    country: "英国",
    city: "London",
    schoolName: "London School of Economics and Political Science",
    programName: "MSc Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "LSE 官网将该项目定义为广义金融硕士，先打牢 corporate finance 与 financial markets 基础，再通过选修课延展到更细分方向。",
    duration: "1 年",
    intake: "秋季",
    keywords: [
      "金融",
      "finance",
      "investment",
      "banking",
      "asset management",
      "corporate finance",
      "风险",
    ],
    tags: ["金融", "投行", "资产管理", "伦敦"],
    overviewUrl: "https://www.lse.ac.uk/study-at-lse/graduate/msc-finance-full-time",
    admissionsUrl: "https://www.lse.ac.uk/study-at-lse/graduate/msc-finance-full-time",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 91,
  },
  {
    id: "edinburgh-education",
    country: "英国",
    city: "Edinburgh",
    schoolName: "The University of Edinburgh",
    programName: "Education MSc",
    degree: "硕士",
    discipline: "教育",
    summary:
      "爱丁堡官网显示，Education MSc 是 Moray House 的旗舰授课型项目，适合希望进入教育政策、研究或实践领域的申请者，也可按方向细分路径。",
    duration: "1 年",
    keywords: [
      "教育",
      "education",
      "teaching",
      "policy",
      "research",
      "教育政策",
      "pedagogy",
    ],
    tags: ["教育", "政策", "研究", "苏格兰"],
    overviewUrl: "https://study.ed.ac.uk/programmes/postgraduate-taught/98-education",
    admissionsUrl: "https://study.ed.ac.uk/programmes/postgraduate-taught/98-education",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 82,
  },
  {
    id: "toronto-mi",
    country: "加拿大",
    city: "Toronto",
    schoolName: "University of Toronto",
    programName: "Master of Information",
    degree: "硕士",
    discipline: "信息 / UX / 数据",
    summary:
      "多伦多大学官网显示，MI 是两年制职业硕士，包含 Human-Centered Data Science、User Experience Design、Information Systems & Design 等多个 concentration。",
    duration: "2 年",
    intake: "秋季",
    keywords: [
      "信息",
      "ux",
      "user experience",
      "data science",
      "human centered data science",
      "information systems",
      "design",
      "hci",
    ],
    tags: ["UX", "数据", "信息系统", "设计"],
    overviewUrl: "https://www.sgs.utoronto.ca/programs/information/",
    admissionsUrl:
      "https://www.sgs.utoronto.ca/future-students/admission-application-requirements/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 84,
  },
  {
    id: "ubc-mban",
    country: "加拿大",
    city: "Vancouver",
    schoolName: "The University of British Columbia",
    programName: "Master of Business Analytics",
    degree: "硕士",
    discipline: "商业分析 / 数据",
    summary:
      "UBC Sauder 官网显示，MBAN 为 12 个月项目，强调将数据转化为可执行商业洞察，并配有 internship、consulting project 或 research project。",
    duration: "12 个月",
    keywords: [
      "商业分析",
      "business analytics",
      "analytics",
      "data",
      "数据",
      "sql",
      "python",
      "strategy",
    ],
    tags: ["商业分析", "数据", "实战项目", "温哥华"],
    overviewUrl: "https://org-www.sauder.ubc.ca/programs/masters-degrees/mban",
    admissionsUrl:
      "https://www.grad.ubc.ca/prospective-students/graduate-degree-programs/Master-of-business-analytics",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 88,
  },
  {
    id: "melbourne-mit",
    country: "澳大利亚",
    city: "Melbourne",
    schoolName: "The University of Melbourne",
    programName: "Master of Information Technology",
    degree: "硕士",
    discipline: "信息技术 / AI",
    summary:
      "墨尔本大学官网显示，MIT 提供 Computing、Cybersecurity、Distributed Computing、Human-Computer Interaction、Artificial Intelligence 等方向，并包含 industry-based learning。",
    duration: "2 年",
    intake: "3 月 / 7 月",
    keywords: [
      "信息技术",
      "it",
      "计算机",
      "artificial intelligence",
      "人工智能",
      "cybersecurity",
      "hci",
      "distributed computing",
    ],
    tags: ["IT", "AI", "HCI", "澳洲八大"],
    overviewUrl:
      "https://study.unimelb.edu.au/find/courses/graduate/master-of-information-technology",
    admissionsUrl:
      "https://study.unimelb.edu.au/find/courses/graduate/master-of-information-technology/entry-requirements",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 87,
  },
  {
    id: "unsw-commerce",
    country: "澳大利亚",
    city: "Sydney",
    schoolName: "UNSW Sydney",
    programName: "Master of Commerce",
    degree: "硕士",
    discipline: "商科 / 金融 / 管理",
    summary:
      "UNSW 官网显示，Master of Commerce 为 1.7 年全日制项目，可在 Finance、Marketing、Business Analytics 等方向中组合专长，课程强调行业实践。",
    duration: "1.7 年",
    keywords: [
      "商科",
      "commerce",
      "金融",
      "finance",
      "marketing",
      "business analytics",
      "management",
      "strategy",
    ],
    tags: ["商科", "金融", "营销", "悉尼"],
    overviewUrl:
      "https://www.unsw.edu.au/study/postgraduate/master-of-commerce?studentType=international",
    admissionsUrl:
      "https://www.unsw.edu.au/study/postgraduate/master-of-commerce?studentType=international",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 78,
  },
  {
    id: "hku-mscs",
    country: "中国香港",
    city: "Hong Kong",
    schoolName: "The University of Hong Kong",
    programName: "Master of Science in Computer Science",
    degree: "硕士",
    discipline: "计算机科学",
    summary:
      "HKU 官网显示，该项目提供 applied 与 fundamental 两类课程，也可进入更加聚焦的 ICT stream，适合希望系统进阶计算机方向的申请者。",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "ai",
      "人工智能",
      "ict",
      "software",
      "data",
    ],
    tags: ["计算机", "港校", "ICT", "AI"],
    overviewUrl: "https://www.msc-cs.hku.hk/",
    admissionsUrl: "https://www.msc-cs.hku.hk/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 89,
  },
  {
    id: "hkust-mfin",
    country: "中国香港",
    city: "Hong Kong",
    schoolName: "The Hong Kong University of Science and Technology",
    programName: "MSc in Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "HKUST 官网将 MSc in Finance 定位为理论与实践并重的金融硕士，强调专业课程训练与行业联系，适合想进入金融相关岗位的学生。",
    keywords: [
      "金融",
      "finance",
      "investment",
      "risk",
      "banking",
      "asset management",
      "fintech",
    ],
    tags: ["金融", "港校", "实务导向", "商学院"],
    overviewUrl: "https://mfin.hkust.edu.hk/",
    admissionsUrl: "https://mfin.hkust.edu.hk/admissions/admissions-requirement",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 90,
  },
  {
    id: "cuhk-marketing",
    country: "中国香港",
    city: "Hong Kong",
    schoolName: "The Chinese University of Hong Kong",
    programName: "MSc in Marketing",
    degree: "硕士",
    discipline: "市场营销",
    summary:
      "CUHK 官网显示，MSc in Marketing 同时覆盖品牌、公关与国际营销，也提供 AI and Quantitative Marketing 路径，适合传统营销与数字营销双向发展。",
    keywords: [
      "市场营销",
      "marketing",
      "传媒",
      "communications",
      "brand",
      "广告",
      "ai marketing",
      "quantitative marketing",
    ],
    tags: ["市场", "品牌", "AI 营销", "港校"],
    overviewUrl: "https://masters.bschool.cuhk.edu.hk/programmes/mscmkt/",
    admissionsUrl:
      "https://masters.bschool.cuhk.edu.hk/programmes/mscmkt/admissions/",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 83,
  },
  {
    id: "nus-mcomp-cs",
    country: "新加坡",
    city: "Singapore",
    schoolName: "National University of Singapore",
    programName: "Master of Computing (Computer Science Specialisation)",
    degree: "硕士",
    discipline: "计算机 / AI",
    summary:
      "NUS 官网显示，MComp CS 让学生深入计算机核心领域与前沿研究，适合希望夯实技术深度并面向 IT 职业进阶的申请者。",
    keywords: [
      "计算机",
      "computer science",
      "cs",
      "ai",
      "人工智能",
      "it",
      "software",
      "computing",
    ],
    tags: ["计算机", "新加坡", "技术深度", "School of Computing"],
    overviewUrl:
      "https://masters.nus.edu.sg/programmes/master-of-computing/mcomp---computer-science-specialisation",
    admissionsUrl:
      "https://masters.nus.edu.sg/programmes/master-of-computing",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 94,
  },
  {
    id: "smu-applied-finance",
    country: "新加坡",
    city: "Singapore",
    schoolName: "Singapore Management University",
    programName: "MSc in Applied Finance",
    degree: "硕士",
    discipline: "金融",
    summary:
      "SMU 官网显示，MAF 聚焦国际与本土金融市场的原理、实践与运作，fresh graduates 也可申请，课程覆盖 financial analytics、sustainable finance 等模块。",
    duration: "18 个月",
    intake: "8 月",
    keywords: [
      "金融",
      "finance",
      "financial analytics",
      "investment",
      "wealth management",
      "sustainable finance",
      "banking",
    ],
    tags: ["金融", "新加坡", "应用导向", "分析"],
    overviewUrl: "https://masters.smu.edu.sg/programme/msc-in-applied-finance",
    admissionsUrl: "https://masters.smu.edu.sg/programme/msc-in-applied-finance",
    checkedAt: STUDY_ABROAD_DATA_UPDATED_AT,
    priority: 85,
  },
];

export const STUDY_ABROAD_COUNTRIES = Array.from(
  new Set(STUDY_ABROAD_PROGRAMS.map((program) => program.country))
);
